trigger:
- master

pool:
  vmImage: 'windows-latest'

variables:
  projects: '**/*.csproj'
  buildConfiguration: 'Release'

steps:
- task: UseDotNet@2
  inputs:
    packageType: 'sdk'
    useGlobalJson: true
  displayName: 'use .net core'

- task: DotNetCoreCLI@2
  inputs:
    command: 'restore'
    projects: '$(projects)'
    feedsToUse: 'select'
  displayName: 'dotnet restore'

- task: DotNetCoreCLI@2
  inputs:
    command: 'build'
    projects: '$(projects)'
    arguments: '--configuration $(BuildConfiguration) --no-restore'
  displayName: 'dotnet build'

- task: DotNetCoreCLI@2
  inputs:
    command: 'pack'
    packagesToPack: '$(projects)'
    nobuild: true
    versioningScheme: 'off'
  displayName: 'dotnet pack'

# - task: DotNetCoreCLI@2
#   inputs:
#     command: 'test'
#     projects: '**/*.Tests/*.csproj'

- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'drop'
    publishLocation: 'Container'
  displayName: 'publish artifacts'
